services:
  postgres:
    image: postgres:16
    container_name: betternetflix-db
    environment:
      POSTGRES_PASSWORD: bettersecret
      POSTGRES_USER: betteruser
      POSTGRES_DB: betternetflix
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d